# docker-compose.yml
services:
  bigsister:
    build: .
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      # Map X11 file for GUI
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Make current host directory available within container as /app
      - .:/app
      # Example for making other directories available
      - ~/Downloads:/Downloads
